/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppHome {
    'textItems': any[];
  }
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface BsMegaMenu {}
  interface BsSlider {
    'image': string;
    'text': string;
    'title': string;
  }
  interface BsTabsShortcodes {}
  interface BsTextBlock {
    'columns': any[];
    'title': string;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLBsMegaMenuElement extends Components.BsMegaMenu, HTMLStencilElement {}
  var HTMLBsMegaMenuElement: {
    prototype: HTMLBsMegaMenuElement;
    new (): HTMLBsMegaMenuElement;
  };

  interface HTMLBsSliderElement extends Components.BsSlider, HTMLStencilElement {}
  var HTMLBsSliderElement: {
    prototype: HTMLBsSliderElement;
    new (): HTMLBsSliderElement;
  };

  interface HTMLBsTabsShortcodesElement extends Components.BsTabsShortcodes, HTMLStencilElement {}
  var HTMLBsTabsShortcodesElement: {
    prototype: HTMLBsTabsShortcodesElement;
    new (): HTMLBsTabsShortcodesElement;
  };

  interface HTMLBsTextBlockElement extends Components.BsTextBlock, HTMLStencilElement {}
  var HTMLBsTextBlockElement: {
    prototype: HTMLBsTextBlockElement;
    new (): HTMLBsTextBlockElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'bs-mega-menu': HTMLBsMegaMenuElement;
    'bs-slider': HTMLBsSliderElement;
    'bs-tabs-shortcodes': HTMLBsTabsShortcodesElement;
    'bs-text-block': HTMLBsTextBlockElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {
    'textItems'?: any[];
  }
  interface AppProfile {
    'match'?: MatchResults;
  }
  interface AppRoot {}
  interface BsMegaMenu {}
  interface BsSlider {
    'image'?: string;
    'text'?: string;
    'title'?: string;
  }
  interface BsTabsShortcodes {}
  interface BsTextBlock {
    'columns'?: any[];
    'title'?: string;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'bs-mega-menu': BsMegaMenu;
    'bs-slider': BsSlider;
    'bs-tabs-shortcodes': BsTabsShortcodes;
    'bs-text-block': BsTextBlock;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'bs-mega-menu': LocalJSX.BsMegaMenu & JSXBase.HTMLAttributes<HTMLBsMegaMenuElement>;
      'bs-slider': LocalJSX.BsSlider & JSXBase.HTMLAttributes<HTMLBsSliderElement>;
      'bs-tabs-shortcodes': LocalJSX.BsTabsShortcodes & JSXBase.HTMLAttributes<HTMLBsTabsShortcodesElement>;
      'bs-text-block': LocalJSX.BsTextBlock & JSXBase.HTMLAttributes<HTMLBsTextBlockElement>;
    }
  }
}


